[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dit"
version = "0.1.0"
authors = [{ name = "Pun Waiwitlikhit" }]
description = "Diffusion Transformer"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["*"]  # package names should match these glob patterns